#!/bin/bash
set -x

PGROOT=`pg_config --bindir`
PATH=$PATH:$PGROOT
DIFFIX_DASHBOARDS_HOME=$HOME/.diffix_dashboards/postgres
DIFFIX_DASHBOARDS_LOGFILE=$DIFFIX_DASHBOARDS_HOME/logfile

pg_ctl -w -D $DIFFIX_DASHBOARDS_HOME -l $DIFFIX_DASHBOARDS_LOGFILE stop
rm -rf $DIFFIX_DASHBOARDS_HOME
