name: Make Build
on:
  push:
    branches:
      - make_build

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build services
        run: npm run build-win
      - name: Add pg_config to PATH # Needed for building `node-libpq`
        run: echo "$env:GITHUB_WORKSPACE\pgsql\bin" >> $env:GITHUB_PATH
      - name: Install node libraries
        run: npm install
      - name: Test
        run: npm test
      - name: Make setup package
        run: npm run make
      - name: Upload setup package
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: out/make/squirrel.windows/x64/*
          retention-days: 15
