name: test_build
on:
  push:
    branches:
      - test_build

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            build-target: linux
          - os: windows-latest
            build-target: win
          - os: macos-latest
            build-target: osx

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install GUI dependencies
        run: npm install
        working-directory: ./gui
      - name: Make GUI
        run: npm run make
        working-directory: ./gui
      - name: Upload GUI ${{ matrix.build-target }} build
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build-target }}
          path: out/make
          retention-days: 10
        working-directory: ./gui
